name: willshex_dart_service_discovery
description: A generic service discovery package.
version: 0.0.1
environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.15.0
  build: ^3.0.0
  source_gen: ^4.0.0
  analyzer: ^8.4.1
  glob: ^2.1.3
  yaml: ^3.1.3
  package_config: ^2.2.0

dev_dependencies:
  test: ^1.24.4
  mockito: ^5.4.4
  build_runner: ^2.4.13
  lints: ^6.0.0
