name: example7_app
description: An app consuming the library package.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  lib_ex7:
    path: ../packages/lib_ex7
  lib_ex7_1:
    path: ../packages/lib_ex7_1
  willshex_dart_service_discovery:
    path: ../../../

dev_dependencies:
  build_runner: ^2.4.0
