name: example9
description: Verification example for abstract/concrete service provider logic.
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  willshex_dart_service_discovery:
    path: ../../

dev_dependencies:
  build_runner: ^2.4.0
  willshex_dart_service_discovery:
    path: ../../
